Alexis12119/nvim-config

lua/plugins/lsp/init.lua
Hi, could you try this? thank you.
=> fix(lsp): make inlayhint keymap work

lua/core/filetypes.lua, lua/plugins/lsp/configs/nvim-lint.lua
=> feat: pre-config `actionlint` 

lua/plugins/cinnamon.lua
=> chore(cinnamon): format the config

init.lua, lua/core/lazy.lua, lua/plugins/lsp/configs/mason.lua, lua/plugins/lsp/configs/nvim-lspconfig.lua, lua/plugins/nvim-cmp.lua, lua/plugins/which-key.lua
=> feat: add option to enable border

lua/plugins/tmux-navigation.lua
=> perf(tmux-navigation): better loading

lua/mappings.lua
=> fix(mappings): improve toggle theme and transparent logic

lua/mappings.lua
oops yesterday Stylua didn't format the code :)
=> chore(mappings): format code

lua/plugins/auto-session.lua
just make it save with git branch. Without it, when switching between git branch, it will fail to restore. 👀
=> feat(auto-session): save with git branch

lua/chadrc.lua, lua/plugins/lsp/configs/nvim-lint.lua
Oops :))
I think it will work fine.
=> feat(statusline): show buffer's linters

lua/core/utils.lua
Add run shell script with bash (:
=> feat(utils): add run "sh"

ftplugin/java.lua, lua/chadrc.lua, lua/core/globals.lua, lua/options.lua, lua/plugins/dap/settings/debugpy.lua, lua/plugins/lsp/settings/jdtls.lua, lua/plugins/rustaceanvim.lua
=> perf: add global variable related to os detection

init.lua, lua/chadrc.lua, lua/plugins/init.lua
I have updated the config to match NvChad config. 
But on my side (personal issue), there's still an error while building base46 module and I don't know why.
https://discord.com/channels/869557815780470834/1301900980886966272
=> feat(nvchad): update ui, base46

ftplugin/dart.lua, lua/plugins/compiler.lua, lua/plugins/dap/settings/java-debug.lua, lua/plugins/toggleterm.lua
=> style: apply style using stylua

lua/core/utils.lua
=> fix(run): run html file

lua/core/commands.lua
=> feat(commands): add JoinEmptyLines, AppendToEnd

GUIDE.md, init.lua, lua/core/env.lua, lua/core/filetypes.lua, lua/options.lua, lua/plugins/auto-session.lua, lua/plugins/colorizer.lua, lua/plugins/comment.lua, lua/plugins/indent-blankline.lua, lua/plugins/init.lua, lua/plugins/lsp/configs/lazydev.lua, lua/plugins/lsp/configs/mason.lua, lua/plugins/lsp/configs/nvim-lint.lua, lua/plugins/lsp/settings/lua_ls.lua, lua/plugins/markdown-preview.lua, lua/plugins/nvim-cmp.lua, lua/plugins/nvim-spectre.lua, lua/plugins/precognition.lua, lua/plugins/sidebar.lua, lua/plugins/sonarlint.lua
- require env before loading lazy in order to use hererock from lazy
- change enabled = false to cond = false to not clone the plugins
- change github action filetype in order to adapt with github action lsp in the future
- mason: prefer lsp's options in lua config (force override default one)
- remove vim schedule wrapper to load mapping
- merge myinit to init?
- move lib lua loaded from lua_ls config to lazydev plugin
---
> [!WARNING]
>
> Please check :)) don't trust me
=> refactor: enhance

GUIDE.md, lua/plugins/auto-session.lua, lua/plugins/colorizer.lua, lua/plugins/comment.lua, lua/plugins/indent-blankline.lua, lua/plugins/init.lua, lua/plugins/lsp/configs/nvim-lint.lua, lua/plugins/markdown-preview.lua, lua/plugins/nvim-cmp.lua, lua/plugins/nvim-spectre.lua, lua/plugins/precognition.lua, lua/plugins/sidebar.lua, lua/plugins/sonarlint.lua, lua/plugins/tmux-navigation.lua
In the previous refactor #79, I have changed enabled to cond which is now I feel not right. Enabled false mean it will not download the plugin, and that is the goal. Cond = false is just temporarily disabled.
=> fix: change cond to enabled

lua/plugins/cinnamon.lua, lua/plugins/diffview.lua, lua/plugins/gitsigns.lua, lua/plugins/indent-blankline.lua, lua/plugins/lsp/configs/conform.lua, lua/plugins/lsp/configs/mason.lua, lua/plugins/lsp/configs/nvim-lint.lua, lua/plugins/lsp/configs/tiny-inline-diagnostic.lua, lua/plugins/lsp/configs/typescript-tools.lua, lua/plugins/marks.lua, lua/plugins/mini-ai.lua, lua/plugins/nvim-surround.lua, lua/plugins/nvim-ufo.lua, lua/plugins/quicker.lua, lua/plugins/rustaceanvim.lua, lua/plugins/supermaven.lua, lua/plugins/todo-comments.lua, lua/plugins/ts-comments.lua
=> refactor: use BufReadPost, BufNewFile instead of VeryLazy

lua/core/globals.lua, lua/plugins/dap/settings/debugpy.lua
For not checking too much if only distinct windows or not
=> refactor: global "is_windows"

ftplugin/dart.lua, lua/plugins/flutter-tools.lua
=> refactor(flutter-tools): use custom lsp capabilities, on_attach

lua/plugins/lsp/configs/mason.lua, lua/plugins/lsp/configs/nvim-lspconfig.lua
=> fix(lsp): Ensure custom LSP configs are used
